version: "3.11"


services:
  app:
    build: ./
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

volumes:
  mongo-data:
