LOAD_TYPES = {
    "uz": ["litr", "kilogram", "dona"],
    "ru": ["литр", "килограмм", "штука"],
    "en": ["litres", "kilogramm", "pieces"],
}
regions = {
    "Toshkent": [
        {
            "name_uz": "Mirzo Ulugʻbek",
            "name_ru": "Мирзо Улугбек",
            "name_en": "Mirzo Ulugbek",
        },
        {"name_uz": "Yunusobod", "name_ru": "Юнусобод", "name_en": "Yunusobod"},
        {
            "name_uz": "Shayxontohur",
            "name_ru": "Шайхонтохур",
            "name_en": "Shaykhontohur",
        },
        {"name_uz": "Chilonzor", "name_ru": "Чиланзар", "name_en": "Chilanzar"},
        {"name_uz": "Yakkasaroy", "name_ru": "Яккасарой", "name_en": "Yakkasaray"},
        {"name_uz": "Mirobod", "name_ru": "Миробод", "name_en": "Mirobod"},
        {"name_uz": "Olmazor", "name_ru": "Олмазор", "name_en": "Olmazor"},
        {"name_uz": "Uchtepa", "name_ru": "Учтепа", "name_en": "Uchtepa"},
        {"name_uz": "Bektemir", "name_ru": "Бектемир", "name_en": "Bektemir"},
        {"name_uz": "Sergeli", "name_ru": "Сергели", "name_en": "Sergeli"},
        {"name_uz": "Hamza", "name_ru": "Хамза", "name_en": "Hamza"},
        {"name_uz": "Qoʻyliq", "name_ru": "Кулик", "name_en": "Koʻylik"},
        {"name_uz": "Bodomzor", "name_ru": "Бодомзор", "name_en": "Bodomzor"},
        {"name_uz": "Chorsu", "name_ru": "Чорсу", "name_en": "Chorsu"},
        {"name_uz": "Kukcha", "name_ru": "Кукча", "name_en": "Kukcha"},
        {"name_uz": "Navza", "name_ru": "Навза", "name_en": "Navza"},
        {"name_uz": "Novza", "name_ru": "Новза", "name_en": "Novza"},
        {"name_uz": "Oʻzbekiston", "name_ru": "Узбекистан", "name_en": "Uzbekistan"},
        {"name_uz": "Tuzel", "name_ru": "Тузель", "name_en": "Tuzel"},
        {"name_uz": "Yangiobod", "name_ru": "Янгиобод", "name_en": "Yangiobod"},
    ],
    "Samarqand": [
        {"name_uz": "Registon", "name_ru": "Регистон", "name_en": "Registon"},
        {"name_uz": "Bibixonim", "name_ru": "Бибиханим", "name_en": "Bibikhanym"},
        {"name_uz": "Qorasuv", "name_ru": "Карасув", "name_en": "Karasuv"},
        {"name_uz": "Chorsu", "name_ru": "Чорсу", "name_en": "Chorsu"},
        {"name_uz": "Siyob", "name_ru": "Сиаб", "name_en": "Siab"},
        {"name_uz": "Kogon", "name_ru": "Когон", "name_en": "Kogon"},
        {"name_uz": "Ishtixon", "name_ru": "Иштихон", "name_en": "Ishtixon"},
        {"name_uz": "Urgut", "name_ru": "Ургут", "name_en": "Urgut"},
        {"name_uz": "Bulungʻur", "name_ru": "Булунгур", "name_en": "Bulungur"},
        {"name_uz": "Nurobod", "name_ru": "Нурабад", "name_en": "Nurabad"},
        {"name_uz": "Payariq", "name_ru": "Пайарык", "name_en": "Payariq"},
        {"name_uz": "Jomboy", "name_ru": "Джамбай", "name_en": "Jomboy"},
        {"name_uz": "Toyloq", "name_ru": "Тойлак", "name_en": "Toylok"},
        {"name_uz": "Kattakoʻl", "name_ru": "Каттакул", "name_en": "Kattakol"},
        {"name_uz": "Xoʻjaobod", "name_ru": "Хужаобод", "name_en": "Khojaobod"},
        {"name_uz": "Afrosiyob", "name_ru": "Афросиаб", "name_en": "Afrosiyob"},
        {"name_uz": "Dahbed", "name_ru": "Дахбед", "name_en": "Dahbed"},
        {"name_uz": "Shahriston", "name_ru": "Шахристан", "name_en": "Shahristan"},
        {"name_uz": "Zarafshon", "name_ru": "Зарафшан", "name_en": "Zarafshan"},
        {"name_uz": "Kurgan", "name_ru": "Курган", "name_en": "Kurgan"},
    ],
    "Buxoro": [
        {"name_uz": "Gʻijduvon", "name_ru": "Гиждуван", "name_en": "Gijduvon"},
        {"name_uz": "Romitan", "name_ru": "Ромитан", "name_en": "Romitan"},
        {"name_uz": "Shofirkon", "name_ru": "Шофиркон", "name_en": "Shofirkon"},
        {"name_uz": "Qorakoʻl", "name_ru": "Каракуль", "name_en": "Qorakoʻl"},
        {"name_uz": "Peshku", "name_ru": "Пешку", "name_en": "Peshku"},
        {"name_uz": "Olot", "name_ru": "Олот", "name_en": "Olot"},
        {"name_uz": "Vobkent", "name_ru": "Вобкент", "name_en": "Vobkent"},
        {"name_uz": "Kogon", "name_ru": "Когон", "name_en": "Kogon"},
        {"name_uz": "Bukhara", "name_ru": "Бухара", "name_en": "Bukhara"},
        {"name_uz": "Karakul", "name_ru": "Каракуль", "name_en": "Karakul"},
        {"name_uz": "Jondor", "name_ru": "Джондор", "name_en": "Jondor"},

        {"name_uz": "Shahrisabz", "name_ru": "Шахрисабз", "name_en": "Shahrisabz"},
        {"name_uz": "Kasbi", "name_ru": "Касби", "name_en": "Kasbi"},
        {"name_uz": "Gʻazli", "name_ru": "Газли", "name_en": "Gazli"},
        {"name_uz": "Zarafshan", "name_ru": "Зарафшан", "name_en": "Zarafshan"},
        {"name_uz": "Karshi", "name_ru": "Карши", "name_en": "Karshi"},
        {"name_uz": "Kattakurgan", "name_ru": "Каттакурган", "name_en": "Kattakurgan"},
        {"name_uz": "Shahrikhan", "name_ru": "Шахрихан", "name_en": "Shahrikhan"},
        {"name_uz": "Kogon", "name_ru": "Когон", "name_en": "Kogon"},
        {
            "name_uz": "Qorovulbozor",
            "name_ru": "Караулбазар",
            "name_en": "Qorovulbozor",
        },
    ],
    "Navoiy": [
        {"name_uz": "Zarafshon", "name_ru": "Зарафшан", "name_en": "Zarafshan"},
        {"name_uz": "Karmana", "name_ru": "Кармана", "name_en": "Karmana"},
        {"name_uz": "Xatirchi", "name_ru": "Хатирчи", "name_en": "Khatirchi"},
        {"name_uz": "Qiziltepa", "name_ru": "Кизилтепа", "name_en": "Kiziltepa"},
        {"name_uz": "Navbahor", "name_ru": "Навбахор", "name_en": "Navbahor"},
        {"name_uz": "Konimex", "name_ru": "Конимех", "name_en": "Konimex"},
        {"name_uz": "Nurota", "name_ru": "Нурат", "name_en": "Nurata"},
        {"name_uz": "Tomdi", "name_ru": "Томди", "name_en": "Tomdi"},
        {"name_uz": "Uchquduq", "name_ru": "Учкудук", "name_en": "Uchkuduk"},
        {"name_uz": "Yangirobot", "name_ru": "Янги Работ", "name_en": "Yangirobot"},
        {"name_uz": "Mingbulak", "name_ru": "Мингбулак", "name_en": "Mingbulak"},
        {"name_uz": "Zomin", "name_ru": "Зомин", "name_en": "Zomin"},
        {"name_uz": "Oqtosh", "name_ru": "Октеш", "name_en": "Oqtosh"},
        {"name_uz": "Qarshi", "name_ru": "Карши", "name_en": "Karshi"},
        {"name_uz": "Shahrisabz", "name_ru": "Шахрисабз", "name_en": "Shahrisabz"},
        {"name_uz": "Kitob", "name_ru": "Китоб", "name_en": "Kitob"},
        {"name_uz": "Nishon", "name_ru": "Нишон", "name_en": "Nishon"},
        {"name_uz": "Chiroqchi", "name_ru": "Чирокчи", "name_en": "Chiroqchi"},
        {"name_uz": "Kasbi", "name_ru": "Касби", "name_en": "Kasbi"},
        {"name_uz": "Yakkabogʻ", "name_ru": "Яккабог", "name_en": "Yakkabog"},
    ],
    "Qashqadaryo": [
        {"name_uz": "Gʻuzor", "name_ru": "Гузар", "name_en": "Guzar"},
        {"name_uz": "Shahrisabz", "name_ru": "Шахрисабз", "name_en": "Shahrisabz"},
        {"name_uz": "Kitob", "name_ru": "Китоб", "name_en": "Kitob"},
        {"name_uz": "Yakkabogʻ", "name_ru": "Яккабог", "name_en": "Yakkabog"},
        {"name_uz": "Nishon", "name_ru": "Нишон", "name_en": "Nishon"},
        {"name_uz": "Qarshi", "name_ru": "Карши", "name_en": "Karshi"},
        {"name_uz": "Mirishkor", "name_ru": "Миришкор", "name_en": "Mirishkor"},
        {"name_uz": "Kasbi", "name_ru": "Касби", "name_en": "Kasbi"},
        {"name_uz": "Muborak", "name_ru": "Мубарак", "name_en": "Muborak"},
        {"name_uz": "Chiroqchi", "name_ru": "Чирокчи", "name_en": "Chiroqchi"},
        {"name_uz": "Qamashi", "name_ru": "Камаши", "name_en": "Kamashi"},
        {"name_uz": "Dehqonobod", "name_ru": "Дехканабад", "name_en": "Dehqonobod"},
        {"name_uz": "Kasan", "name_ru": "Касан", "name_en": "Kasan"},
        {"name_uz": "Kitob", "name_ru": "Китоб", "name_en": "Kitob"},
        {"name_uz": "Koson", "name_ru": "Косон", "name_en": "Koson"},
        {"name_uz": "Shakhrisabz", "name_ru": "Шахрисабз", "name_en": "Shakhrisabz"},
        {"name_uz": "Yangiobod", "name_ru": "Янгиобод", "name_en": "Yangiobod"},
        {"name_uz": "Qarshi", "name_ru": "Карши", "name_en": "Karshi"},
        {"name_uz": "Yakkabogʻ", "name_ru": "Яккабог", "name_en": "Yakkabog"},
        {"name_uz": "Muborak", "name_ru": "Мубарак", "name_en": "Muborak"},
    ],
    "Surxondaryo": [
        {"name_uz": "Termiz", "name_ru": "Термез", "name_en": "Termiz"},
        {"name_uz": "Denov", "name_ru": "Денов", "name_en": "Denov"},

        {"name_uz": "Sherobod", "name_ru": "Шеробод", "name_en": "Sherobod"},
        {"name_uz": "Uzun", "name_ru": "Узун", "name_en": "Uzun"},
        {"name_uz": "Shoʻrchi", "name_ru": "Шурчи", "name_en": "Shoʻrchi"},
        {"name_uz": "Qumqoʻrgʻon", "name_ru": "Кумкурган", "name_en": "Qumqoʻrgʻon"},
        {"name_uz": "Boysun", "name_ru": "Байсун", "name_en": "Boysun"},
        {"name_uz": "Sariosiyo", "name_ru": "Сариосийо", "name_en": "Sariosiyo"},
        {"name_uz": "Oltinsoy", "name_ru": "Алтинсой", "name_en": "Oltinsoy"},
        {"name_uz": "Bandixon", "name_ru": "Бандихон", "name_en": "Bandixon"},
        {"name_uz": "Jarqoʻrgʻon", "name_ru": "Джаркурган", "name_en": "Jarqoʻrgʻon"},
        {"name_uz": "Muzrabot", "name_ru": "Музрабат", "name_en": "Muzrabot"},
        {"name_uz": "Angor", "name_ru": "Ангор", "name_en": "Angor"},
        {"name_uz": "Denov", "name_ru": "Денов", "name_en": "Denov"},
        {"name_uz": "Qiziriq", "name_ru": "Кизирик", "name_en": "Qiziriq"},
        {"name_uz": "Shoʻrchi", "name_ru": "Шурчи", "name_en": "Shoʻrchi"},
        {"name_uz": "Muzrabot", "name_ru": "Музрабат", "name_en": "Muzrabot"},
        {"name_uz": "Uzun", "name_ru": "Узун", "name_en": "Uzun"},
        {"name_uz": "Sariosiyo", "name_ru": "Сариосийо", "name_en": "Sariosiyo"},
        {"name_uz": "Oltinsoy", "name_ru": "Алтинсой", "name_en": "Oltinsoy"},
    ],
    "Andijon": [
        {"name_uz": "Andijon", "name_ru": "Андижан", "name_en": "Andijan"},
        {"name_uz": "Asaka", "name_ru": "Асака", "name_en": "Asaka"},
        {"name_uz": "Baliqchi", "name_ru": "Балыкчи", "name_en": "Balikchi"},
        {"name_uz": "Boʻz", "name_ru": "Боз", "name_en": "Boʻz"},
        {"name_uz": "Buloqboshi", "name_ru": "Булокбоши", "name_en": "Buloqboshi"},
        {"name_uz": "Izboskan", "name_ru": "Избаскан", "name_en": "Izboskan"},
        {"name_uz": "Jalaquduq", "name_ru": "Джалакудук", "name_en": "Jalaquduq"},
        {"name_uz": "Xoʻjaobod", "name_ru": "Ходжаобод", "name_en": "Khojaobod"},
        {"name_uz": "Marhamat", "name_ru": "Мархамат", "name_en": "Marhamat"},
        {"name_uz": "Oltinkoʻl", "name_ru": "Олтинкуль", "name_en": "Oltinkoʻl"},
        {"name_uz": "Paxtaobod", "name_ru": "Пахтаабад", "name_en": "Paxtaobod"},
        {"name_uz": "Qoʻrgʻontepa", "name_ru": "Кургантепа", "name_en": "Qoʻrgʻontepa"},
        {"name_uz": "Shahrixon", "name_ru": "Шахрихан", "name_en": "Shahrixon"},
        {"name_uz": "Ulugʻnor", "name_ru": "Улугнор", "name_en": "Ulugʻnor"},
        {"name_uz": "Xonobod", "name_ru": "Ханабад", "name_en": "Khanabad"},
        {"name_uz": "Qorasuv", "name_ru": "Карасу", "name_en": "Karasu"},
        {"name_uz": "Andijon", "name_ru": "Андижан", "name_en": "Andijan"},
        {"name_uz": "Asaka", "name_ru": "Асака", "name_en": "Asaka"},
        {"name_uz": "Baliqchi", "name_ru": "Балыкчи", "name_en": "Balikchi"},
        {"name_uz": "Boʻz", "name_ru": "Боз", "name_en": "Boʻz"},
    ],
    "Fargʻona": [
        {"name_uz": "Fargʻona", "name_ru": "Фергана", "name_en": "Fergana"},
        {"name_uz": "Margʻilon", "name_ru": "Маргилан", "name_en": "Margilan"},
        {"name_uz": "Qoʻqon", "name_ru": "Коканд", "name_en": "Kokand"},
        {"name_uz": "Buvayda", "name_ru": "Бувайда", "name_en": "Buvayda"},
        {"name_uz": "Dangʻara", "name_ru": "Дангара", "name_en": "Dangara"},
        {"name_uz": "Furqat", "name_ru": "Фуркат", "name_en": "Furqat"},
        {"name_uz": "Oltiariq", "name_ru": "Алтыарык", "name_en": "Oltiariq"},
        {"name_uz": "Rishton", "name_ru": "Риштан", "name_en": "Rishton"},
        {"name_uz": "Soʻx", "name_ru": "Сох", "name_en": "Sokh"},
        {"name_uz": "Toshloq", "name_ru": "Ташлак", "name_en": "Tashlak"},
        {"name_uz": "Uchkoʻprik", "name_ru": "Учкуприк", "name_en": "Uchkuprik"},
        {"name_uz": "Yozyovon", "name_ru": "Йозёвон", "name_en": "Yozyovon"},
        {"name_uz": "Quva", "name_ru": "Кува", "name_en": "Quva"},
        {"name_uz": "Beshariq", "name_ru": "Бешарык", "name_en": "Besharik"},

        {"name_uz": "Bogʻdod", "name_ru": "Багдад", "name_en": "Baghdad"},
        {"name_uz": "Quvasoy", "name_ru": "Кувасай", "name_en": "Quvasoy"},
        {"name_uz": "Vodil", "name_ru": "Водил", "name_en": "Vodil"},
        {"name_uz": "Yaypan", "name_ru": "Яйпан", "name_en": "Yaypan"},
        {"name_uz": "Chimyon", "name_ru": "Чимган", "name_en": "Chimgan"},
        {
            "name_uz": "Yangi Margʻilon",
            "name_ru": "Янги Маргилан",
            "name_en": "Yangi Margilan",
        },
    ],
    "Namangan": [
        {"name_uz": "Namangan", "name_ru": "Наманган", "name_en": "Namangan"},
        {"name_uz": "Pop", "name_ru": "Поп", "name_en": "Pop"},
        {"name_uz": "Kosonsoy", "name_ru": "Касансой", "name_en": "Kosonsoy"},
        {"name_uz": "Chortoq", "name_ru": "Чартак", "name_en": "Chartak"},
        {"name_uz": "Mingbuloq", "name_ru": "Мингбулок", "name_en": "Mingbulok"},
        {"name_uz": "Norin", "name_ru": "Норин", "name_en": "Norin"},
        {"name_uz": "Toʻraqoʻrgʻon", "name_ru": "Туракурган", "name_en": "Turakurgan"},
        {"name_uz": "Uychi", "name_ru": "Уйчи", "name_en": "Uychi"},
        {
            "name_uz": "Yangiqoʻrgʻon",
            "name_ru": "Янги Курган",
            "name_en": "Yangikurgan",
        },
        {"name_uz": "Uychi", "name_ru": "Уйчи", "name_en": "Uychi"},
        {"name_uz": "Norin", "name_ru": "Норин", "name_en": "Norin"},
        {"name_uz": "Uchqoʻrgʻon", "name_ru": "Учкурган", "name_en": "Uchkurgan"},
        {"name_uz": "Chust", "name_ru": "Чуст", "name_en": "Chust"},
        {"name_uz": "Kosonsoy", "name_ru": "Касансой", "name_en": "Kosonsoy"},
        {"name_uz": "Pop", "name_ru": "Поп", "name_en": "Pop"},
        {"name_uz": "Toʻraqoʻrgʻon", "name_ru": "Туракурган", "name_en": "Turakurgan"},
        {
            "name_uz": "Yangiqoʻrgʻon",
            "name_ru": "Янги Курган",
            "name_en": "Yangikurgan",
        },
        {"name_uz": "Mingbuloq", "name_ru": "Мингбулок", "name_en": "Mingbulok"},
        {"name_uz": "Chortoq", "name_ru": "Чартак", "name_en": "Chartak"},
        {"name_uz": "Norin", "name_ru": "Норин", "name_en": "Norin"},
    ],
    "Sirdaryo": [
        {"name_uz": "Guliston", "name_ru": "Гулистан", "name_en": "Gulistan"},
        {"name_uz": "Sirdaryo", "name_ru": "Сырдаря", "name_en": "Sirdarya"},
        {"name_uz": "Boyovut", "name_ru": "Баяут", "name_en": "Bayaut"},
        {"name_uz": "Yangier", "name_ru": "Янгиер", "name_en": "Yangier"},
        {"name_uz": "Sardoba", "name_ru": "Сардоба", "name_en": "Sardoba"},
        {"name_uz": "Mirzaobod", "name_ru": "Мирзаабад", "name_en": "Mirzaobod"},
        {"name_uz": "Sayhunobod", "name_ru": "Сайхунобод", "name_en": "Saykhunabad"},
        {"name_uz": "Shirin", "name_ru": "Ширин", "name_en": "Shirin"},
        {"name_uz": "Xovos", "name_ru": "Ховос", "name_en": "Khovos"},
        {"name_uz": "Navbahor", "name_ru": "Навбахор", "name_en": "Navbahor"},
        {"name_uz": "Istiqlol", "name_ru": "Истиклол", "name_en": "Istiqlol"},
        {"name_uz": "Nurafshon", "name_ru": "Нурафшан", "name_en": "Nurafshon"},
        {"name_uz": "Yangiyer", "name_ru": "Янгиер", "name_en": "Yangiyer"},
        {"name_uz": "Baxt", "name_ru": "Бахт", "name_en": "Baxt"},
        {"name_uz": "Sayhun", "name_ru": "Сайхун", "name_en": "Sayhun"},
        {"name_uz": "Sirdaryo", "name_ru": "Сырдаря", "name_en": "Sirdaryo"},
        {"name_uz": "Boyovut", "name_ru": "Баяут", "name_en": "Bayaut"},
        {"name_uz": "Guliston", "name_ru": "Гулистан", "name_en": "Gulistan"},
        {"name_uz": "Mirzaobod", "name_ru": "Мирзаабад", "name_en": "Mirzaobod"},
        {"name_uz": "Sayhunobod", "name_ru": "Сайхунобод", "name_en": "Saykhunabad"},
    ],
    "Xorazm": [
        {"name_uz": "Urgench", "name_ru": "Ургенч", "name_en": "Urgench"},
        {"name_uz": "Khiva", "name_ru": "Хива", "name_en": "Khiva"},
        {"name_uz": "Yangibozor", "name_ru": "Янгибозор", "name_en": "Yangibozor"},
        {"name_uz": "Gurlan", "name_ru": "Гурлан", "name_en": "Gurlan"},

        {"name_uz": "Shavat", "name_ru": "Шават", "name_en": "Shavat"},
        {"name_uz": "Rishtan", "name_ru": "Риштан", "name_en": "Rishton"},
        {"name_uz": "Xiva", "name_ru": "Хива", "name_en": "Khiva"},
        {"name_uz": "Hazarasp", "name_ru": "Хазорасп", "name_en": "Hazarasp"},
        {"name_uz": "Urganch", "name_ru": "Ургенч", "name_en": "Urganch"},
        {"name_uz": "Yangiariq", "name_ru": "Янгиариқ", "name_en": "Yangiariq"},
        {"name_uz": "Beruniy", "name_ru": "Беруни", "name_en": "Beruni"},
        {"name_uz": "Shumanay", "name_ru": "Шуманай", "name_en": "Shumanay"},
        {"name_uz": "Khojaqali", "name_ru": "Ходжейли", "name_en": "Khojaly"},
        {"name_uz": "Gurlan", "name_ru": "Гурлан", "name_en": "Gurlan"},
        {"name_uz": "Yangibozor", "name_ru": "Янгибозор", "name_en": "Yangibozor"},
        {"name_uz": "Shavat", "name_ru": "Шават", "name_en": "Shavat"}
    ]
}
