ITEMS_PER_PAGE = 8
LANGUAGE = {"🇺🇿 O'zbekcha": "uz", "🇷🇺 Русский": "ru", "🇬🇧 English": "en"}
LOAD_TYPES = {
    "uz": ["litr", "kilogram", "dona"],
    "ru": ["литр", "килограмм", "штука"],
    "en": ["litres", "kilogramm", "pieces"],
}
regions = {
    "en": {
        "Tashkent": [
            "Olmazor",
            "Yangiobod",
            "Tuzel",
            "Bodomzor",
            "Hamza",
            "Koʻylik",
            "Novza",
            "Kukcha",
            "Bektemir",
            "Chorsu",
            "Mirobod",
            "Chilanzar",
            "Uzbekistan",
            "Uchtepa",
            "Shaykhontohur",
            "Yakkasaray",
            "Navza",
            "Sergeli",
            "Mirzo Ulugbek",
            "Yunusobod",
        ],
        "Samarqand": [
            "Kattakol",
            "Siab",
            "Bulungur",
            "Zarafshan",
            "Ishtixon",
            "Jomboy",
            "Shahristan",
            "Chorsu",
            "Afrosiyob",
            "Kurgan",
            "Kogon",
            "Khojaobod",
            "Urgut",
            "Dahbed",
            "Toylok",
            "Registon",
            "Nurabad",
            "Payariq",
            "Karasuv",
            "Bibikhanym",
        ],
        "Bukhara": [
            "Vobkent",
            "Kasbi",
            "Zarafshan",
            "Romitan",
            "Olot",
            "Jondor",
            "Bukhara",
            "Shofirkon",
            "Shahrikhan",
            "Peshku",
            "Shahrisabz",
            "Qorakoʻl",
            "Kogon",
            "Gijduvon",
            "Kattakurgan",
            "Gazli",
            "Karakul",
            "Qorovulbozor",
            "Karshi",
        ],
        "Navoiy": [
            "Kitob",
            "Konimex",
            "Kasbi",
            "Zarafshan",
            "Yakkabog",
            "Oqtosh",
            "Khatirchi",
            "Karmana",
            "Mingbulak",
            "Uchkuduk",
            "Nurata",
            "Shahrisabz",
            "Chiroqchi",
            "Karshi",
            "Zomin",
            "Tomdi",
            "Kiziltepa",
            "Navbahor",
            "Yangirobot",
            "Nishon",
        ],
        "Qashqadaryo": [
            "Shahrisabz",
            "Kitob",
            "Yakkabog",
            "Koson",
            "Kasan",
            "Kamashi",
            "Muborak",
            "Yangiobod",
            "Guzar",
            "Kasbi",
            "Mirishkor",
            "Shakhrisabz",
            "Nishon",
            "Chiroqchi",
            "Dehqonobod",
            "Karshi",
        ],
        "Surkhandaryo": [
            "Uzun",
            "Muzrabot",
            "Sherobod",
            "Oltinsoy",
            "Qumqoʻrgʻon",
            "Shoʻrchi",
            "Boysun",
            "Termiz",
            "Sariosiyo",
            "Qiziriq",
            "Jarqoʻrgʻon",
            "Denov",
            "Bandixon",
            "Angor",
        ],
        "Andijan": [
            "Ulugʻnor",
            "Balikchi",
            "Qoʻrgʻontepa",
            "Oltinkoʻl",
            "Shahrixon",
            "Jalaquduq",
            "Boʻz",
            "Khojaobod",
            "Buloqboshi",
            "Paxtaobod",
            "Asaka",
            "Izboskan",
            "Andijan",
            "Marhamat",
            "Khanabad",
            "Karasu",
        ],
        "Fergana": [
            "Chimgan",
            "Yaypan",
            "Tashlak",
            "Uchkuprik",
            "Quvasoy",
            "Quva",
            "Rishton",
            "Buvayda",
            "Kokand",
            "Dangara",
            "Margilan",
            "Oltiariq",
            "Fergana",
            "Baghdad",
            "Besharik",
            "Sokh",
            "Vodil",
            "Yozyovon",
            "Yangi Margilan",
            "Furqat",
        ],
        "Namangan": [
            "Norin",
            "Pop",
            "Yangikurgan",
            "Chust",
            "Namangan",
            "Chartak",
            "Turakurgan",
            "Uychi",
            "Kosonsoy",
            "Mingbulok",
            "Uchkurgan",
        ],
    },
    "ru": {
        "Ташкент": [
            "Хамза",
            "Янгиобод",
            "Кукча",
            "Мирзо Улугбек",
            "Бектемир",
            "Узбекистан",
            "Сергели",
            "Юнусабад",
            "Яккасарай",
            "Чиланзар",
            "Алмазар",
            "Мирабад",
            "Навза",
            "Чорсу",
            "Шайхонтохур",
            "Новза",
            "Бадамзар",
            "Тузель",
            "Учтепа",
            "Куйлюк",
        ],
        "Самарканд": [
            "Шахристан",
            "Афросиаб",
            "Джамбай",
            "Бибиханум",
            "Сиаб",
            "Тойлак",
            "Ходжаобод",
            "Ургут",
            "Карасу",
            "Нурабад",
            "Каттакуль",
            "Булунгур",
            "Регистан",
            "Иштыхан",
            "Зарафшан",
            "Дахбед",
            "Курган",
            "Пайарык",
            "Чорсу",
            "Каган",
        ],
        "Бухара": [
            "Алат",
            "Пешку",
            "Вабкент",
            "Касби",
            "Газли",
            "Шафиркан",
            "Зарафшан",
            "Каракуль",
            "Гиждуван",
            "Каттакурган",
            "Караулбазар",
            "Ромитан",
            "Шахрисабз",
            "Шахрихан",
            "Карши",
            "Бухара",
            "Каган",
            "Жондор",
        ],
        "Навои": [
            "Учкудук",
            "Шахрисабз",
            "Нурата",
            "Конимех",
            "Касби",
            "Кармана",
            "Хатирчи",
            "Тамды",
            "Нишон",
            "Зарафшан",
            "Мингбулак",
            "Зомин",
            "Карши",
            "Янгиработ",
            "Китаб",
            "Октош",
            "Навбахор",
            "Кизилтепа",
            "Чиракчи",
            "Яккабог",
        ],
        "Кашкадарья": [
            "Камаши",
            "Касби",
            "Муборак",
            "Дехканабад",
            "Нишон",
            "Миришкор",
            "Касан",
            "Гузар",
            "Чиракчи",
            "Янгиобод",
            "Шахрисабз",
            "Яккабог",
            "Косон",
            "Карши",
            "Китаб",
        ],
        "Сурхандарья": [
            "Денау",
            "Алтынсай",
            "Узун",
            "Шурчи",
            "Музработ",
            "Кумкурган",
            "Кизирик",
            "Термез",
            "Сариасия",
            "Шерабад",
            "Джаркурган",
            "Бандихан",
            "Ангор",
            "Байсун",
        ],
        "Андижан": [
            "Булокбоши",
            "Андижан",
            "Пахтаабад",
            "Избаскан",
            "Кургантепа",
            "Боз",
            "Ханабад",
            "Улугнор",
            "Баликчи",
            "Шахрихан",
            "Ходжаобод",
            "Маргилан",
            "Джалакудук",
            "Олтынкуль",
            "Карасу",
            "Асака",
        ],
        "Фергана": [
            "Фергана",
            "Кува",
            "Риштан",
            "Маргилан",
            "Кувасай",
            "Учкуприк",
            "Чимган",
            "Сох",
            "Янги Маргилан",
            "Ёзёван",
            "Коканд",
            "Фуркат",
            "Ташлак",
            "Дангар",
            "Алтыарык",
            "Бувайда",
            "Бешарык",
            "Багдад",
            "Яйпан",
            "Водил",
        ],
        "Наманган": [
            "Нарын",
            "Учкурган",
            "Поп",
            "Чуст",
            "Косонсой",
            "Чартак",
            "Уйчи",
            "Мингбулак",
            "Янгикурган",
            "Наманган",
            "Туракурган",
        ],
    },
    "uz": {
        "Toshkent": [
            "Mirzo Ulugʻbek",
            "Olmazor",
            "Yangiobod",
            "Tuzel",
            "Chilonzor",
            "Qoʻyliq",
            "Oʻzbekiston",
            "Bodomzor",
            "Hamza",
            "Novza",
            "Kukcha",
            "Shayxontohur",
            "Bektemir",
            "Chorsu",
            "Mirobod",
            "Yakkasaroy",
            "Yunusobod",
            "Navza",
            "Sergeli",
            "Uchtepa",
        ],
        "Samarqand": [
            "Bulungʻur",
            "Ishtixon",
            "Toyloq",
            "Qorasuv",
            "Jomboy",
            "Xoʻjaobod",
            "Bibixonim",
            "Shahriston",
            "Chorsu",
            "Afrosiyob",
            "Kurgan",
            "Zarafshon",
            "Kogon",
            "Urgut",
            "Nurobod",
            "Dahbed",
            "Registon",
            "Payariq",
            "Kattakoʻl",
            "Siyob",
        ],
        "Buxoro": [
            "Vobkent",
            "Kasbi",
            "Romitan",
            "Olot",
            "Jondor",
            "Gʻijduvon",
            "Qarshi",
            "Shofirkon",
            "Shahrikhan",
            "Peshku",
            "Shahrisabz",
            "Qorakoʻl",
            "Gʻazli",
            "Zarafshon",
            "Kogon",
            "Kattakurgan",
            "Karakul",
            "Qorovulbozor",
            "Buxoro",
        ],
        "Navoiy": [
            "Kitob",
            "Konimex",
            "Kasbi",
            "Xatirchi",
            "Qiziltepa",
            "Oqtosh",
            "Uchquduq",
            "Qarshi",
            "Karmana",
            "Nurota",
            "Mingbulak",
            "Shahrisabz",
            "Zarafshon",
            "Chiroqchi",
            "Yakkabogʻ",
            "Zomin",
            "Tomdi",
            "Navbahor",
            "Yangirobot",
            "Nishon",
        ],
        "Qashqadaryo": [
            "Shahrisabz",
            "Kitob",
            "Dehqonobod",
            "Koson",
            "Qarshi",
            "Kasan",
            "Muborak",
            "Yangiobod",
            "Qamashi",
            "Kasbi",
            "Mirishkor",
            "Shakhrisabz",
            "Nishon",
            "Chiroqchi",
            "Gʻuzor",
            "Yakkabogʻ",
        ],
        "Surxondaryo": [
            "Uzun",
            "Muzrabot",
            "Sherobod",
            "Oltinsoy",
            "Qumqoʻrgʻon",
            "Shoʻrchi",
            "Boysun",
            "Termiz",
            "Sariosiyo",
            "Qiziriq",
            "Jarqoʻrgʻon",
            "Denov",
            "Bandixon",
            "Angor",
        ],
        "Andijon": [
            "Andijon",
            "Ulugʻnor",
            "Xonobod",
            "Qorasuv",
            "Qoʻrgʻontepa",
            "Xoʻjaobod",
            "Oltinkoʻl",
            "Jalaquduq",
            "Boʻz",
            "Baliqchi",
            "Buloqboshi",
            "Paxtaobod",
            "Asaka",
            "Izboskan",
            "Marhamat",
            "Shahrixon",
        ],
        "Fargʻona": [
            "Yaypan",
            "Fargʻona",
            "Quvasoy",
            "Dangʻara",
            "Quva",
            "Toshloq",
            "Rishton",
            "Buvayda",
            "Qoʻqon",
            "Chimyon",
            "Margʻilon",
            "Oltiariq",
            "Yangi Margʻilon",
            "Bagʻdod",
            "Besharik",
            "Vodiy",
            "Soʻx",
            "Uchkoʻprik",
            "Yozyovon",
            "Furqat",
        ],
        "Namangan": [
            "Chortoq",
            "Norin",
            "Pop",
            "Chust",
            "Namangan",
            "Toʻraqoʻrgʻon",
            "Uychi",
            "Yangiqoʻrgʻon",
            "Kosonsoy",
            "Mingbulok",
            "Uchqoʻrgʻon",
        ],
    },
}
